### ISSUE TITLE
Unable to open CHANGELOG

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/vsc-material-theme#95]
![changelog-issue](https://user-images.githubusercontent.com/20873402/30912105-2962765e-a340-11e7-886b-2c11351e132d.gif)

Full Message:

```
Unable to open 'Preview 'CHANGELOG.md'': cannot open file://%5Cc:\users\user\.vscode\extensions\equinusocio.vsc-material-theme-1.0.3\changelog.md. Detail: Invalid file resource (file://%5Cc:\users\user\.vscode\extensions\equinusocio.vsc-material-theme-1.0.3\changelog.md).
```

**Comment by OctoD** [comment]
Should be fixed in dev branch. @equinusocio @Zx-EvM

**Comment by Shaker-Hamdi** [comment]
I have the same issue.

**Comment by equinusocio** [comment]
@OctoD where is the commit fix?

**Comment by Zx-EvM** [comment]
@equinusocio @OctoD hello. Can you reopen this issue? In VSCode 1.17.0 and MT 1.0.4 this problem still presents.
